name: Test

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: 'Browser'
        options:
        - 'chrome'
        - 'firefox'

env:
  TEST: ${{ site.github.url }}

jobs:
  nightwatch:
    name: Nightwatch
    runs-on: ubuntu-latest
    timeout-minutes: 150

    steps:
    - uses: actions/checkout@master
    - name: Test
      run: |
        ls
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
